### ISSUE TITLE
Update cc.yaml with new specifications

### ISSUE THREAD

**Issue by pepitoenpeligro** [pepitoenpeligro/CloudBanking#45]
lenguaje:

```yaml
lenguaje:
  - rust

test:
  - src/bankaccount/test.rs
  - src/bankcard/test.rs
  - src/bankfund/test.rs
  - src/controller/test.rs
  - src/paymentgroup/test.rs
  - src/savinggroup/test.rs
  - src/user/test.rs
  - src/utils/test.rs

fichero_tareas:
  - make.toml
```
