### ISSUE TITLE
Config CI alternative {CircleCi, Jenkins,...}

### ISSUE THREAD

**Issue by pepitoenpeligro** [pepitoenpeligro/cloudbanking#62]

**Comment by pepitoenpeligro** [comment]
Circle.ci

![07](https://user-images.githubusercontent.com/14912971/99920284-bbede480-2d22-11eb-9044-8ad0ce8dd571.png)

**Comment by pepitoenpeligro** [comment]
Drone.io

![18](https://user-images.githubusercontent.com/14912971/99920338-18510400-2d23-11eb-8887-0beb822af942.png)

**Comment by pepitoenpeligro** [comment]
Github Action

```yaml
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --nocapture
```
