### ISSUE TITLE
Config Travis

### ISSUE THREAD

**Issue by pepitoenpeligro** [pepitoenpeligro/cloudbanking#63]

**Comment by pepitoenpeligro** [comment]
Travis

```yaml
sudo: false

language: rust

cache: cargo

branches:
  only:
  - master

rust:
  - 1.47.0

script:
  cargo test
```
