### ISSUE TITLE
Automatic Infrastructure Provisioning and Environment Configuration

### ISSUE THREAD

**Issue by pepitoenpeligro** [pepitoenpeligro/cloudbanking#79]
I want some method to request infrastructure (with code) and configure the environment of my infrastructure.

I am thinking in vagrant + sensible

**Comment by pepitoenpeligro** [comment]
For local configuration and provisioning: 
```ruby
Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"
    # config.vm.hostname = "ubuntu-rust"
  
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  
    #SSH forward port 22 -> 2222
    config.vm.network "forwarded_port", guest: 22, host:2222, id: "ssh", auto_correct: true
  
    #Expose port 80 -> 8080 for web Service (future)
    config.vm.network "forwarded_port", guest: 80, host:80, id: "web", auto_correct: true

    #Expose port 80 -> 8080 for web Service (future)
    config.vm.network "forwarded_port", guest: 443, host:443, id: "websecure", auto_correct: true
    
    #Expose port 3030 -> 3030 for api Service (future)
    config.vm.network "forwarded_port", guest: 3030, host:3030, id: "service1", auto_correct: true
  
    #Expose port 3031 -> 3031 for api Service (future)
    config.vm.network "forwarded_port", guest: 3031, host:3031, id: "service2", auto_correct: true

    #Expose port 3032 -> 3032 for api Service (future)
    config.vm.network "forwarded_port", guest: 3032, host:3032, id: "service3", auto_correct: true

    #Expose port 3033 -> 3033 for api Service (future)
    config.vm.network "forwarded_port", guest: 3033, host:3033, id: "service4", auto_correct: true
  
    config.vm.provision :ansible do |ansible|
      ansible.limit = "all"
      ansible.playbook = "provision.yaml"
      # ansible.verbose = "v"
    end
  
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024

    end
  
  end
```

**Comment by pepitoenpeligro** [comment]
As I have a OVH open cloud account and I know how to describe infrastructure as code with OpenStack:


```ruby 
require 'vagrant-openstack-provider'

 
Vagrant.configure('2') do |config|

  #SSH forward port 22 -> 2222
  config.vm.network "forwarded_port", guest: 22, host:2222, id: "ssh", auto_correct: true

  #Expose port 80 -> 8080 for web Service (future)
  config.vm.network "forwarded_port", guest: 443, host:443, id: "websecure", auto_correct: true
  
  #Expose port 3030 -> 3030 for api Service (future)
  config.vm.network "forwarded_port", guest: 3030, host:3030, id: "service1", auto_correct: true

  #Expose port 3031 -> 3031 for api Service (future)
  config.vm.network "forwarded_port", guest: 3031, host:3031, id: "service2", auto_correct: true

  #Expose port 3032 -> 3032 for api Service (future)
  config.vm.network "forwarded_port", guest: 3032, host:3032, id: "service3", auto_correct: true

  #Expose port 3033 -> 3033 for api Service (future)
  config.vm.network "forwarded_port", guest: 3033, host:3033, id: "service4", auto_correct: true

  
  config.vm.define :'vagrant-ubuntu' do |v|
 
    v.ssh.username = 'ubuntu'
    v.ssh.private_key_path = '~/.ssh/ovh'
    v.ssh.insert_key = 'false'
    v.vm.synced_folder '.', '/vagrant', type: 'rsync', disabled: true
    v.vm.provider :openstack do |provider|
      provider.openstack_auth_url    = ENV['OS_AUTH_URL']
      provider.openstack_network_url = 'https://network.compute.uk1.cloud.ovh.net/v2.0'
      provider.identity_api_version  = ENV['OS_IDENTITY_API_VERSION']
      provider.username              = ENV['OS_USERNAME']
      provider.password              = ENV['OS_PASSWORD']
      provider.domain_name           = ENV['OS_USER_DOMAIN_NAME']
      provider.project_name          = ENV['OS_PROJECT_NAME']
      provider.tenant_name           = ENV['OS_TENANT_NAME']
      provider.project_domain_name   = ENV['OS_USER_DOMAIN_NAME']
      provider.flavor                = 's1-4'
      provider.image                 = 'Ubuntu 18.04'
      provider.keypair_name          = 'ovh'
      provider.region                = ENV['OS_REGION_NAME']
      provider.networks              = [ 'Ext-Net' ]
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.limit = "all"
    ansible.playbook = "provision.yaml"
    # ansible.verbose = "v"
  end
end
```

**Comment by pepitoenpeligro** [comment]
For local and remote environment configuration: 

```
---
- hosts: all
  user: pepitoenpeligro
  become: yes

  vars:
    - packages: ['build-essential', 'git', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'dkms', 'wget', 'unzip']
    - project_location: /home/pepitoenpeligro

  tasks:
  # - name: Apt update
  #   apt: name=foobar state=installed
  #   register: apt_status
  #   until: apt_status is success
  #   delay: 6
  #   retries: 10

  - name: Say hi
    shell: echo "hi"!

  - name: Remove locks
    shell: rm -f /var/lib/apt/lists/lock && rm -f /var/lib/dpkg/lock && rm -f /var/cache/apt/archives/lock && rm -rf /var/lib/dpkg/lock-frontend


  # - name: Remove apt lock file
  #   file:
  #     state: absent
  #     path: "/var/lib/dpkg/lock" 

  # - name: Remove apt lock file
  #   file:
  #     state: absent
  #     path: "/var/lib/dpkg/lock-frontend" 


  - name: Update APT Cache
    apt:
      update_cache: yes
      force_apt_get: yes  

  # - name: Install {{ packages }}
  #   become: yes

  #   apt:
  #     name: "{{ packages }}"
  #     state: present
  #     update_cache: yes

  - name: Get gpg docker.
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

  - name: Add repository.
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && apt update
  
  - name: Remove locks
    shell: rm -f /var/lib/apt/lists/lock && rm -f /var/lib/dpkg/lock && rm -f /var/cache/apt/archives/lock && rm -rf /var/lib/dpkg/lock-frontend


  - name: Install Docker.
    become_user: root
    shell: apt-get install docker-ce -y


  - name: Make User docker
    become_user: root
    shell: gpasswd -a ubuntu docker

  - name: Docker service start
    service:
      name: docker
      state: started
  
  - name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755
```
